#!/bin/bash

# Get the current route without the file://
current_path=$(echo "$NAUTILUS_SCRIPT_SELECTED_URIS" | sed 's/^file:\/\///')

# Check if the current_path is a directory
if [ -d "$current_path" ]; then
    current_path="$current_path"
else
    current_path=$(dirname "$current_path")
fi

cd "$current_path" && warp-terminal
